### ISSUE TITLE
ssl_error_rx_record_too_long when using HTTPS

### ISSUE THREAD

**Issue by ouw-jvt** [drud/ddev-browsersync#18]
Hello!

Thanks for your work on this project! It works great for http:// protocol, but for the life of me I can't get it to behave with https://

In firefox I get an 
```ssl_error_rx_record_too_long``` message when viewing the page. In chrome it just says "ssl protocol error".

Switching to http fixes this, but all of my stuff is configured for HTTPS so it's a bit inconvienent!

Some more details:

- blank WordPress project
- no config alterations to wordpress, ddev, or browsersync
- macos

Have you run into this issue before? It could be something more related to my machine, or ddev as a whole, rather than this project.

**Comment by rfay** [comment]
One factoid about DDEV v1.20.0 @tyler36 is that now that NVM_NODENODE_EXTRA_CA_CERTS is set inside the container, nodejs can trust info coming from php apps. Not sure if that helps us with this class of problem or not.

**Comment by tyler36** [comment]
Thank you for logging the issue @ouw-jvt 

There was a discussing over on Discord about wether its possible with DDEV. https://discord.com/channels/664580571770388500/1004741861291855892

Browsersync supports HTTPS though using certificate/key pairs but this wont work because ddev-router doen't know how to reverse-porxy https.

**Comment by ouw-jvt** [comment]
> Thank you for logging the issue @ouw-jvt
> 
> There was a discussing over on Discord about wether its possible with DDEV. https://discord.com/channels/664580571770388500/1004741861291855892
> 
> Browsersync supports HTTPS though using certificate/key pairs but this wont work because ddev-router doen't know how to reverse-porxy https.

That was me in discord chatting about the issue :)

I've settled with http-only for now. Not ideal, but it still works great for everything I need so far. Hopefully I don't run into anything that _needs_ https - I haven't really yet, but CORS is a bugger sometimes.


Thank you both for your work on the ddev project and ecosystem.
