### ISSUE TITLE
LaravelMix example: process.env.DDEV_HOSTNAME only works without additional project hostnames

### ISSUE THREAD

**Issue by mandrasch** [drud/ddev-browsersync#27]
Hey, just as information, thanks for providing this:

Laravel Mix example (https://github.com/drud/ddev-browsersync#laravel-mix-configuration) suggests using

```javascript
let url = process.env.DDEV_HOSTNAME;

mix.js('resources/js/app.js', 'public/js')
    .postCss('resources/css/app.css', 'public/css', [
        //
    ])
    .browserSync({
        proxy: "localhost",
        host:  url,
        open:  false,
        ui: false
    });
```

When there are [Additional Hostnames](https://ddev.readthedocs.io/en/latest/users/extend/additional-hostnames/) configured in DDEV, `DDEV_HOSTNAME` returns a comma separated list. 

For example `main-site.ddev.site,subsite-1.ddev.site,subsite-2.ddev.site`

We also noticed that `host` can be disabled all together and integration of browsersync still works? (I guess because proxy is used anyway and host is only for cli terminal output). So maybe we could leave it out of the example to avoid confusion? Not quite sure yet. 🤔 

```javascript

mix.js('resources/js/app.js', 'public/js')
    .postCss('resources/css/app.css', 'public/css', [
        //
    ])
    .browserSync({
        proxy: "localhost",
        open:  false,
        ui: false
    });
```

https://browsersync.io/docs/options#option-host

Best regards,
Matthias
PS: I could provide a sample repo if needed for reproduction.

**Comment by tyler36** [comment]
Thanks @mandrasch . 

Any interest in a PR?

**Comment by mandrasch** [comment]
Docs:
- https://browsersync.io/docs/options#option-host ("// Override host detection if you know the correct IP to use")
- https://laravel-mix.com/docs/6.0/browsersync (doesn't use `host` as well)

**Comment by tyler36** [comment]
@mandrasch 

I was able to replicate the issue you describe. It occures with the laravel-mix and the vanilla javascript included.

I did a PR which explicity sets the URL (as suggested by @rfay ) and includes a docs update on additional hostnames.  I prefer to see a project-based URL instead of an IP-based URL, which would be the case if we dropped the `host` config option.

How common are additional hostname projects? I think the PR works but it breaks auto-updates so perhaps a better solution is required.

**Comment by rfay** [comment]
There are quite a lot of uses for additional_hostnames and additional_fqdns.

**Comment by tyler36** [comment]
Change the PR to support addition hostnames out of the box. 

@mandrasch does that work for you?

**Comment by mandrasch** [comment]
> Change the PR to support addition hostnames out of the box.
> 
> @mandrasch does that work for you?

Hey sorry for the delay, can I install your updated PR as well with `ddev get https://github.com/tyler36/ddev-browsersync/tarball/tyler36/https-support/` to test it? 

(Test repo https://github.com/mandrasch/ddev-laravelmix-browsersync)

**Comment by mandrasch** [comment]
Just tried, doesn't work anymore: `Unable to download https://github.com/tyler36/ddev-browsersync/tarball/tyler36/https-support/: Unable to download https://github.com/tyler36/ddev-browsersync/tarball/tyler36/https-support/: download link https://github.com/tyler36/ddev-browsersync/tarball/tyler36/https-support/ returned wrong status code: got 404 want 200 `

**Comment by tyler36** [comment]
@mandrasch 

I think the tarbar for #21 is: `ddev get https://github.com/drud/ddev-browsersync/tarball/tyler36/https-support`

**Comment by mandrasch** [comment]
Thanks very much, I pulled latest version into https://github.com/mandrasch/ddev-laravelmix-browsersync, did not change much in my repo. Still worked. 

For my personal use cases I'll go without setting the host since I see no benefit in setting this (and also think it is confusing to read 'http://my-ddev-site.ddev.site' instead of 'https://').

```javascript
mix.browserSync({
    proxy: "localhost",
    open: false,
    ui: false
});
```

Thanks very much for the discussion here! Much appreciated! 🙏  🙏
