### ISSUE TITLE
No auto refresh for Laravel mix

### ISSUE THREAD

**Issue by marflow** [drud/ddev-browsersync#37]
I think I followed the docs for use with Laravel Mix but I have to reload manually to see changes applied to the html (with Tailwind CSS) when using `ddev exec npm run watch`. Using `ddev browsersync`works automatically, but I need the css file to be build fresh with Laravel Mix. Guess I am missing something obvious. Thanks for pointers.

**Comment by tyler36** [comment]
@marflow 

It sounds like you haven't setup a Tailwind watcher yet.

For Laravel-mix, you'll need to follow the steps at https://tailwindcss.com/docs/guides/laravel#mix.

You'll end up with a `webpack.mix.js` _similar_ to the below.

```js
let url = 'browsersync-demo.ddev.site';

mix.js('resources/js/app.js', 'public/js')
    .postCss('resources/css/app.css', 'public/css', [
       require("tailwindcss"),
    ])
    .browserSync({
        proxy: url,
        host:  url,
        open:  false,
    });
```

As for `ddev browsersync`, this watches for changes. You'll need to start some sort of Tailwind CLI build process that adds the new Tailwind CSS.  See https://tailwindcss.com/docs/installation. 

Laravel-mix is easier though.

**Comment by marflow** [comment]
Thanks a lot for your fast feedback, @tyler36! 

Maybe I explained it a bit complicated, but the mix part is working, a new Tailwind CSS is always generated. The browser just is not refreshing automatically, I have to manually do that. Then I get the "Browsersync: connected" insert (which already shows after starting with `ddev exec npm run watch`). 

Could it be an error in `browser-sync.js`? I have this
```
// #ddev-generated
let docroot = process.env.DDEV_DOCROOT;
let filesdir = process.env.DDEV_FILES_DIR;
let url = process.env.DDEV_HOSTNAME;

if (filesdir === "") {
    filesdir = null
}

module.exports = {

    files: ["/resources/**/*.antlers.html" ],
    ignore: ["node_modules", filesdir, "vendor"],
    open: false,
    ui: false,
    server: false,
    proxy: {
        target: "localhost"
    },
    host: url,
}
```

**Comment by tyler36** [comment]
@marflow  thanks for the update.

You need to update your webpack.mix.js:

```
    .browserSync({
        files: ['/resources/**/*.antlers.html'],
        proxy: url,
        host: url,
        open: false,
    });
```

## Background

This addon is designed to provide the browsersync app and `browser-sync.js` to run it.

When you use Laravel-mix, your using this addons browsersync app, but the browsersync config from `webpack.mix.js`.
The `browser-sync.js` file is _not_ used when running through Laravel-mix.

**Comment by tyler36** [comment]
You can find the default values for Laravel-mix in `node_modules/laravel-mix/src/components/BrowserSync.js`.

**Comment by marflow** [comment]
Thanks again @tyler36 for the fast help and explanation – works like a charm now! (In the meantime, I found I could use `*.antlers.php` as well, but now I can go back to "main stream" again :)

**Comment by tyler36** [comment]
Glad you got it working!

**Comment by tyler36** [comment]
Yeah, the default watched files are:

```js
'app/**/*.php',
'resources/views/**/*.php',
`${this.context.config.publicPath || 'public'}/**/*.(js|css)`
```

**Comment by toddprouty** [comment]
@tyler36, this thread was very helpful in getting DDEV/Browsersync working with Laravel Mix ([this comment](https://github.com/drud/ddev-browsersync/issues/37#issuecomment-1381142627) in particular). I have one related question: Is it necessary to run browsersync via DDEV _and_ run the Mix watch process in order for auto-refresh to work? I am running the following in two separate terminals:

**Terminal 1:**
``` 
ddev browsersync
```
**Terminal 2:**
```
ddev npm run watch
```

With both of these running, browser refresh is initiated when files in the specified folders are changed. If one or the other is _not_ running, refresh does not happen. If this isn't correct, I can create a separate issue to address it.

**Comment by marflow** [comment]
Hello Todd, it should work without running `ddev browsersync`. What maybe the issue is that I start npm watch a little different: `ddev exec npm run watch`, like in the docs. Then you should have the browser reloading at `https://your-project.ddev.site:3000`. If it does not maybe your first `ddev browsersync` process is still working and the mix reloads on `...:3001`. But if you restart ddev it should work with port 3000. Hope you get it going!

**Comment by toddprouty** [comment]
Thanks, @marflow, but that didn't work for me. I tried that command, but because package.json is in a subfolder on this (very old) project, I have to run it like this: `ddev exec --dir /var/www/html/site npm run watch`. That _appears_ to work at first: the build process runs each time a watched file is changed. But the browser does not auto-refresh. If I combine that command with `ddev browsersync` (run first in a separate terminal), it works as described in my previous comment. The browser reloads automatically. 

Here's what my config looks like:
```javascript
let url = 'some-host.test';

mix
    .sourceMaps(false, 'inline-source-map')
    // Dashboard/Administration CSS
    .postCss('src/css/dashboard.css', 'public_html/assets/css')
    // Marketing/Simple CSS
    .postCss('src/css/marketing.css', 'public_html/assets/css')
    // Main Website
    .js('src/js/app.js', 'public_html/build/js') // main website
    .sass('src/sass/app.scss', 'public_html/build/css') // main website
    .options({
        processCssUrls: false,
        postCss: [ tailwindcss('tailwind.config.js') ],
    })
    .browserSync({
        files: [
            "public_html/build/{*,**/*}",
            "craft/templates/**/*.+(html|twig)"
        ],
        proxy: url,
        host:  url,
        open:  false
    });
```

**Comment by marflow** [comment]
Hm, I have not tried it with my Craft projects, so I do not know what might be needed in addition. Have you asked on Craft Discord? DDEV is recommended for Craft now so I would there must be devs that have set it up already. Another small difference may be worth trying, is to remove `host: url,` my config looks like this:
```
	.browserSync({
		files: ['resources/**/*.antlers.html'],
		proxy: url,
		open: false
	})
	.version();
```
May be worth a try?

**Comment by toddprouty** [comment]
That did the trick! It reloads automatically now without the need to run `ddev browsersync`. 

For some reason, it only reloads when changes are made in the first set of files (CSS/JS), not the second (Craft/Twig templates). This was also the case when I was running both commands. 

``` JS
files: [
    "public_html/build/{*,**/*}", // triggers refresh
    "craft/templates/**/*.+(html|twig)" // no refresh
    "craft/templates/{*,**/*}" // variation on glob - no refresh
],
```
But this is probably unrelated to the DDEV add-on. You're right, Craft Discord might be a good place to ask about this. Thanks for your help!

**Comment by marflow** [comment]
No problem, glad you are able to get it working even partially :) Regarding the set of files, the second line has no ending `,` . Maybe that makes a difference. Also, maybe you could try every line on it´s own or change the order to narrow the problem down. If not somebody on Discord will be able to help you out.

**Comment by tyler36** [comment]
@toddprouty You don't need to run both; just one or the other.

If you use Lavarvel mix, you'll need to update `webpack.mix.js` to manage your config. Laravel mix then passes the config through to this add-on. 

If it triggering on `public_html/build/{*,**/*}`, but not `craft/templates/**/*.+(html|twig)`, it means the addon is functioning correctly.  Double-check the paths are correctly.
